# Generated by Django 4.0.4 on 2022-06-19 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=20)),
                ('btitle', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cdody', models.CharField(max_length=150)),
                ('bcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm', to='blog.blog')),
            ],
        ),
    ]
