# Generated by Django 4.0.4 on 2022-06-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='aname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='btitle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cdody',
            field=models.CharField(max_length=250),
        ),
    ]
