# Generated by Django 4.0.4 on 2022-07-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_aname_alter_blog_btitle_alter_blog_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cdody',
            new_name='cbody',
        ),
    ]
