# Generated by Django 4.0.4 on 2022-07-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='suggestion',
            new_name='suggestions',
        ),
    ]
