# Generated by Django 4.0.4 on 2022-07-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_suggestion_feedback_suggestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedback1',
        ),
    ]
