# Generated by Django 4.0.4 on 2022-07-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_feedback_feedback1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback1',
            new_name='Feedback',
        ),
    ]
